Feature/add services
faasj/gateway pull request #18
Opened 2021-06-10 15:43 UTC by aleshagram

добавил пакеты с сервисами и репозитериями, указал связь между ними

2021-06-10 15:50 UTC, i7bro commented on src/main/java/com/faasj/gateway/repository/FunctionRepository.java
> +    public List<FunctionDto> getAll() {
Мы из БД dto достаем или уже с entity работаем?

2021-06-10 17:04 UTC, r331 commented on src/main/java/com/faasj/gateway/repository/FunctionRepository.java
> +    public List<FunctionDto> getAll() {
В дб мы сущности храним. Туда дто не надо складывать

2021-06-11 08:01 UTC, i7bro commented on src/main/java/com/faasj/gateway/repository/FunctionRepository.java
> +    public FunctionDto getById() {
Тут наверно надо передать id в метод

2021-06-11 08:03 UTC, i7bro commented on src/main/java/com/faasj/gateway/repository/FunctionRepository.java
> +    public FunctionDto delete() {
этот метод можно сделать void.

2021-06-11 08:07 UTC, i7bro commented on src/main/java/com/faasj/gateway/repository/FunctionRepository.java
> +public class FunctionRepository {
Надо всё же заимплементить CrudRepo или другие реализации, JpaRepo например

2021-06-11 08:08 UTC, i7bro commented on src/main/java/com/faasj/gateway/repository/FunctionRepository.java
> +public class FunctionRepository {
Или потом?

2021-06-12 13:01 UTC, i7bro approved these changes

2021-06-12 13:26 UTC, r331 requested changes

2021-06-12 13:26 UTC, r331 commented on src/main/java/com/faasj/gateway/repository/FunctionRepository.java
> +public class FunctionRepository {
Этот класс не нужен

2021-06-12 13:26 UTC, r331 commented on src/main/java/com/faasj/gateway/repository/FunctionRepositoryInterface.java
> +public interface FunctionRepositoryInterface extends CrudRepository<FunctionEntity, UUID> {
Лучше оставить просто FunctionRepository.

2021-06-12 13:26 UTC, r331 commented on src/main/java/com/faasj/gateway/repository/ProjectRepository.java
> +public class ProjectRepository {
Класс не нужен

2021-06-12 13:26 UTC, r331 commented on src/main/java/com/faasj/gateway/service/FunctionService.java
> +    public void save(FunctionEntity functionEntity) {
Метод должен принимать дто, преобразовывать в сущность и сохранять

2021-06-12 13:26 UTC, r331 commented on src/main/java/com/faasj/gateway/service/ProjectService.java
> +    public void save(ProjectEntity projectEntity) {
Метод должен принимать дто, преобразовывать в сущность и сохранять

2021-06-14 08:05 UTC, r331 approved these changes

2021-06-14 15:46 UTC, merged